// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/swift-descriptor.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_google_2fprotobuf_2fswift_2ddescriptor_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_google_2fprotobuf_2fswift_2ddescriptor_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fswift_2ddescriptor_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
namespace google {
namespace protobuf {
class LinkedObject;
class LinkedObjectDefaultTypeInternal;
extern LinkedObjectDefaultTypeInternal _LinkedObject_default_instance_;
class SwiftEnumOptions;
class SwiftEnumOptionsDefaultTypeInternal;
extern SwiftEnumOptionsDefaultTypeInternal _SwiftEnumOptions_default_instance_;
class SwiftFieldOptions;
class SwiftFieldOptionsDefaultTypeInternal;
extern SwiftFieldOptionsDefaultTypeInternal _SwiftFieldOptions_default_instance_;
class SwiftFileOptions;
class SwiftFileOptionsDefaultTypeInternal;
extern SwiftFileOptionsDefaultTypeInternal _SwiftFileOptions_default_instance_;
class SwiftMessageOptions;
class SwiftMessageOptionsDefaultTypeInternal;
extern SwiftMessageOptionsDefaultTypeInternal _SwiftMessageOptions_default_instance_;
}  // namespace protobuf
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> ::google::protobuf::LinkedObject* Arena::CreateMaybeMessage<::google::protobuf::LinkedObject>(Arena*);
template<> ::google::protobuf::SwiftEnumOptions* Arena::CreateMaybeMessage<::google::protobuf::SwiftEnumOptions>(Arena*);
template<> ::google::protobuf::SwiftFieldOptions* Arena::CreateMaybeMessage<::google::protobuf::SwiftFieldOptions>(Arena*);
template<> ::google::protobuf::SwiftFileOptions* Arena::CreateMaybeMessage<::google::protobuf::SwiftFileOptions>(Arena*);
template<> ::google::protobuf::SwiftMessageOptions* Arena::CreateMaybeMessage<::google::protobuf::SwiftMessageOptions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace google {
namespace protobuf {

enum AccessControl : int {
  InternalEntities = 0,
  PublicEntities = 1
};
bool AccessControl_IsValid(int value);
constexpr AccessControl AccessControl_MIN = InternalEntities;
constexpr AccessControl AccessControl_MAX = PublicEntities;
constexpr int AccessControl_ARRAYSIZE = AccessControl_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccessControl_descriptor();
template<typename T>
inline const std::string& AccessControl_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AccessControl>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AccessControl_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AccessControl_descriptor(), enum_t_value);
}
inline bool AccessControl_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AccessControl* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AccessControl>(
    AccessControl_descriptor(), name, value);
}
enum RealmOverrideRepeated : int {
  OVERRIDE = 0,
  APPEND = 1
};
bool RealmOverrideRepeated_IsValid(int value);
constexpr RealmOverrideRepeated RealmOverrideRepeated_MIN = OVERRIDE;
constexpr RealmOverrideRepeated RealmOverrideRepeated_MAX = APPEND;
constexpr int RealmOverrideRepeated_ARRAYSIZE = RealmOverrideRepeated_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RealmOverrideRepeated_descriptor();
template<typename T>
inline const std::string& RealmOverrideRepeated_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RealmOverrideRepeated>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RealmOverrideRepeated_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RealmOverrideRepeated_descriptor(), enum_t_value);
}
inline bool RealmOverrideRepeated_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RealmOverrideRepeated* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RealmOverrideRepeated>(
    RealmOverrideRepeated_descriptor(), name, value);
}
// ===================================================================

class LinkedObject PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.protobuf.LinkedObject) */ {
 public:
  inline LinkedObject() : LinkedObject(nullptr) {}
  virtual ~LinkedObject();

  LinkedObject(const LinkedObject& from);
  LinkedObject(LinkedObject&& from) noexcept
    : LinkedObject() {
    *this = ::std::move(from);
  }

  inline LinkedObject& operator=(const LinkedObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline LinkedObject& operator=(LinkedObject&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LinkedObject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LinkedObject* internal_default_instance() {
    return reinterpret_cast<const LinkedObject*>(
               &_LinkedObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LinkedObject& a, LinkedObject& b) {
    a.Swap(&b);
  }
  inline void Swap(LinkedObject* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LinkedObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LinkedObject* New() const final {
    return CreateMaybeMessage<LinkedObject>(nullptr);
  }

  LinkedObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LinkedObject>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LinkedObject& from);
  void MergeFrom(const LinkedObject& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LinkedObject* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.protobuf.LinkedObject";
  }
  protected:
  explicit LinkedObject(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto);
    return ::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldNameFieldNumber = 1,
    kFromTypeFieldNumber = 2,
    kPropertyNameFieldNumber = 3,
  };
  // required string fieldName = 1;
  bool has_fieldname() const;
  private:
  bool _internal_has_fieldname() const;
  public:
  void clear_fieldname();
  const std::string& fieldname() const;
  void set_fieldname(const std::string& value);
  void set_fieldname(std::string&& value);
  void set_fieldname(const char* value);
  void set_fieldname(const char* value, size_t size);
  std::string* mutable_fieldname();
  std::string* release_fieldname();
  void set_allocated_fieldname(std::string* fieldname);
  private:
  const std::string& _internal_fieldname() const;
  void _internal_set_fieldname(const std::string& value);
  std::string* _internal_mutable_fieldname();
  public:

  // required string fromType = 2;
  bool has_fromtype() const;
  private:
  bool _internal_has_fromtype() const;
  public:
  void clear_fromtype();
  const std::string& fromtype() const;
  void set_fromtype(const std::string& value);
  void set_fromtype(std::string&& value);
  void set_fromtype(const char* value);
  void set_fromtype(const char* value, size_t size);
  std::string* mutable_fromtype();
  std::string* release_fromtype();
  void set_allocated_fromtype(std::string* fromtype);
  private:
  const std::string& _internal_fromtype() const;
  void _internal_set_fromtype(const std::string& value);
  std::string* _internal_mutable_fromtype();
  public:

  // required string propertyName = 3;
  bool has_propertyname() const;
  private:
  bool _internal_has_propertyname() const;
  public:
  void clear_propertyname();
  const std::string& propertyname() const;
  void set_propertyname(const std::string& value);
  void set_propertyname(std::string&& value);
  void set_propertyname(const char* value);
  void set_propertyname(const char* value, size_t size);
  std::string* mutable_propertyname();
  std::string* release_propertyname();
  void set_allocated_propertyname(std::string* propertyname);
  private:
  const std::string& _internal_propertyname() const;
  void _internal_set_propertyname(const std::string& value);
  std::string* _internal_mutable_propertyname();
  public:

  // @@protoc_insertion_point(class_scope:google.protobuf.LinkedObject)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fieldname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fromtype_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr propertyname_;
  friend struct ::TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
};
// -------------------------------------------------------------------

class SwiftFileOptions PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.protobuf.SwiftFileOptions) */ {
 public:
  inline SwiftFileOptions() : SwiftFileOptions(nullptr) {}
  virtual ~SwiftFileOptions();

  SwiftFileOptions(const SwiftFileOptions& from);
  SwiftFileOptions(SwiftFileOptions&& from) noexcept
    : SwiftFileOptions() {
    *this = ::std::move(from);
  }

  inline SwiftFileOptions& operator=(const SwiftFileOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SwiftFileOptions& operator=(SwiftFileOptions&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SwiftFileOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SwiftFileOptions* internal_default_instance() {
    return reinterpret_cast<const SwiftFileOptions*>(
               &_SwiftFileOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SwiftFileOptions& a, SwiftFileOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(SwiftFileOptions* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SwiftFileOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SwiftFileOptions* New() const final {
    return CreateMaybeMessage<SwiftFileOptions>(nullptr);
  }

  SwiftFileOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SwiftFileOptions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SwiftFileOptions& from);
  void MergeFrom(const SwiftFileOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SwiftFileOptions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.protobuf.SwiftFileOptions";
  }
  protected:
  explicit SwiftFileOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto);
    return ::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClassPrefixFieldNumber = 1,
    kGenerateStructFieldNumber = 4,
    kGenerateRealmObjectsFieldNumber = 5,
    kGenerateReactFieldNumber = 6,
    kEntitiesAccessControlFieldNumber = 2,
    kCompileForFrameworkFieldNumber = 3,
  };
  // optional string class_prefix = 1;
  bool has_class_prefix() const;
  private:
  bool _internal_has_class_prefix() const;
  public:
  void clear_class_prefix();
  const std::string& class_prefix() const;
  void set_class_prefix(const std::string& value);
  void set_class_prefix(std::string&& value);
  void set_class_prefix(const char* value);
  void set_class_prefix(const char* value, size_t size);
  std::string* mutable_class_prefix();
  std::string* release_class_prefix();
  void set_allocated_class_prefix(std::string* class_prefix);
  private:
  const std::string& _internal_class_prefix() const;
  void _internal_set_class_prefix(const std::string& value);
  std::string* _internal_mutable_class_prefix();
  public:

  // optional bool generate_struct = 4 [default = false];
  bool has_generate_struct() const;
  private:
  bool _internal_has_generate_struct() const;
  public:
  void clear_generate_struct();
  bool generate_struct() const;
  void set_generate_struct(bool value);
  private:
  bool _internal_generate_struct() const;
  void _internal_set_generate_struct(bool value);
  public:

  // optional bool generate_realm_objects = 5 [default = false];
  bool has_generate_realm_objects() const;
  private:
  bool _internal_has_generate_realm_objects() const;
  public:
  void clear_generate_realm_objects();
  bool generate_realm_objects() const;
  void set_generate_realm_objects(bool value);
  private:
  bool _internal_generate_realm_objects() const;
  void _internal_set_generate_realm_objects(bool value);
  public:

  // optional bool generate_react = 6 [default = false];
  bool has_generate_react() const;
  private:
  bool _internal_has_generate_react() const;
  public:
  void clear_generate_react();
  bool generate_react() const;
  void set_generate_react(bool value);
  private:
  bool _internal_generate_react() const;
  void _internal_set_generate_react(bool value);
  public:

  // optional .google.protobuf.AccessControl entities_access_control = 2 [default = PublicEntities];
  bool has_entities_access_control() const;
  private:
  bool _internal_has_entities_access_control() const;
  public:
  void clear_entities_access_control();
  ::google::protobuf::AccessControl entities_access_control() const;
  void set_entities_access_control(::google::protobuf::AccessControl value);
  private:
  ::google::protobuf::AccessControl _internal_entities_access_control() const;
  void _internal_set_entities_access_control(::google::protobuf::AccessControl value);
  public:

  // optional bool compile_for_framework = 3 [default = true];
  bool has_compile_for_framework() const;
  private:
  bool _internal_has_compile_for_framework() const;
  public:
  void clear_compile_for_framework();
  bool compile_for_framework() const;
  void set_compile_for_framework(bool value);
  private:
  bool _internal_compile_for_framework() const;
  void _internal_set_compile_for_framework(bool value);
  public:

  // @@protoc_insertion_point(class_scope:google.protobuf.SwiftFileOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr class_prefix_;
  bool generate_struct_;
  bool generate_realm_objects_;
  bool generate_react_;
  int entities_access_control_;
  bool compile_for_framework_;
  friend struct ::TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
};
// -------------------------------------------------------------------

class SwiftMessageOptions PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.protobuf.SwiftMessageOptions) */ {
 public:
  inline SwiftMessageOptions() : SwiftMessageOptions(nullptr) {}
  virtual ~SwiftMessageOptions();

  SwiftMessageOptions(const SwiftMessageOptions& from);
  SwiftMessageOptions(SwiftMessageOptions&& from) noexcept
    : SwiftMessageOptions() {
    *this = ::std::move(from);
  }

  inline SwiftMessageOptions& operator=(const SwiftMessageOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SwiftMessageOptions& operator=(SwiftMessageOptions&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SwiftMessageOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SwiftMessageOptions* internal_default_instance() {
    return reinterpret_cast<const SwiftMessageOptions*>(
               &_SwiftMessageOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SwiftMessageOptions& a, SwiftMessageOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(SwiftMessageOptions* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SwiftMessageOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SwiftMessageOptions* New() const final {
    return CreateMaybeMessage<SwiftMessageOptions>(nullptr);
  }

  SwiftMessageOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SwiftMessageOptions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SwiftMessageOptions& from);
  void MergeFrom(const SwiftMessageOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SwiftMessageOptions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.protobuf.SwiftMessageOptions";
  }
  protected:
  explicit SwiftMessageOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto);
    return ::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLinkedObjectsFieldNumber = 5,
    kAdditionalClassNameFieldNumber = 4,
    kGenerateErrorTypeFieldNumber = 1,
    kGenerateRealmObjectFieldNumber = 2,
    kGenerateReactFieldNumber = 3,
  };
  // repeated .google.protobuf.LinkedObject linkedObjects = 5;
  int linkedobjects_size() const;
  private:
  int _internal_linkedobjects_size() const;
  public:
  void clear_linkedobjects();
  ::google::protobuf::LinkedObject* mutable_linkedobjects(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::protobuf::LinkedObject >*
      mutable_linkedobjects();
  private:
  const ::google::protobuf::LinkedObject& _internal_linkedobjects(int index) const;
  ::google::protobuf::LinkedObject* _internal_add_linkedobjects();
  public:
  const ::google::protobuf::LinkedObject& linkedobjects(int index) const;
  ::google::protobuf::LinkedObject* add_linkedobjects();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::protobuf::LinkedObject >&
      linkedobjects() const;

  // optional string additional_class_name = 4;
  bool has_additional_class_name() const;
  private:
  bool _internal_has_additional_class_name() const;
  public:
  void clear_additional_class_name();
  const std::string& additional_class_name() const;
  void set_additional_class_name(const std::string& value);
  void set_additional_class_name(std::string&& value);
  void set_additional_class_name(const char* value);
  void set_additional_class_name(const char* value, size_t size);
  std::string* mutable_additional_class_name();
  std::string* release_additional_class_name();
  void set_allocated_additional_class_name(std::string* additional_class_name);
  private:
  const std::string& _internal_additional_class_name() const;
  void _internal_set_additional_class_name(const std::string& value);
  std::string* _internal_mutable_additional_class_name();
  public:

  // optional bool generate_error_type = 1 [default = false];
  bool has_generate_error_type() const;
  private:
  bool _internal_has_generate_error_type() const;
  public:
  void clear_generate_error_type();
  bool generate_error_type() const;
  void set_generate_error_type(bool value);
  private:
  bool _internal_generate_error_type() const;
  void _internal_set_generate_error_type(bool value);
  public:

  // optional bool generate_realm_object = 2 [default = false];
  bool has_generate_realm_object() const;
  private:
  bool _internal_has_generate_realm_object() const;
  public:
  void clear_generate_realm_object();
  bool generate_realm_object() const;
  void set_generate_realm_object(bool value);
  private:
  bool _internal_generate_realm_object() const;
  void _internal_set_generate_realm_object(bool value);
  public:

  // optional bool generate_react = 3 [default = false];
  bool has_generate_react() const;
  private:
  bool _internal_has_generate_react() const;
  public:
  void clear_generate_react();
  bool generate_react() const;
  void set_generate_react(bool value);
  private:
  bool _internal_generate_react() const;
  void _internal_set_generate_react(bool value);
  public:

  // @@protoc_insertion_point(class_scope:google.protobuf.SwiftMessageOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::protobuf::LinkedObject > linkedobjects_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr additional_class_name_;
  bool generate_error_type_;
  bool generate_realm_object_;
  bool generate_react_;
  friend struct ::TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
};
// -------------------------------------------------------------------

class SwiftFieldOptions PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.protobuf.SwiftFieldOptions) */ {
 public:
  inline SwiftFieldOptions() : SwiftFieldOptions(nullptr) {}
  virtual ~SwiftFieldOptions();

  SwiftFieldOptions(const SwiftFieldOptions& from);
  SwiftFieldOptions(SwiftFieldOptions&& from) noexcept
    : SwiftFieldOptions() {
    *this = ::std::move(from);
  }

  inline SwiftFieldOptions& operator=(const SwiftFieldOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SwiftFieldOptions& operator=(SwiftFieldOptions&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SwiftFieldOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SwiftFieldOptions* internal_default_instance() {
    return reinterpret_cast<const SwiftFieldOptions*>(
               &_SwiftFieldOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SwiftFieldOptions& a, SwiftFieldOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(SwiftFieldOptions* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SwiftFieldOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SwiftFieldOptions* New() const final {
    return CreateMaybeMessage<SwiftFieldOptions>(nullptr);
  }

  SwiftFieldOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SwiftFieldOptions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SwiftFieldOptions& from);
  void MergeFrom(const SwiftFieldOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SwiftFieldOptions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.protobuf.SwiftFieldOptions";
  }
  protected:
  explicit SwiftFieldOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto);
    return ::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRealmIndexedPropertieFieldNumber = 1,
    kRealmPrimaryKeyFieldNumber = 2,
    kRealmOverridePropertieFieldNumber = 3,
  };
  // optional bool realm_indexed_propertie = 1 [default = false];
  bool has_realm_indexed_propertie() const;
  private:
  bool _internal_has_realm_indexed_propertie() const;
  public:
  void clear_realm_indexed_propertie();
  bool realm_indexed_propertie() const;
  void set_realm_indexed_propertie(bool value);
  private:
  bool _internal_realm_indexed_propertie() const;
  void _internal_set_realm_indexed_propertie(bool value);
  public:

  // optional bool realm_primary_key = 2 [default = false];
  bool has_realm_primary_key() const;
  private:
  bool _internal_has_realm_primary_key() const;
  public:
  void clear_realm_primary_key();
  bool realm_primary_key() const;
  void set_realm_primary_key(bool value);
  private:
  bool _internal_realm_primary_key() const;
  void _internal_set_realm_primary_key(bool value);
  public:

  // optional .google.protobuf.RealmOverrideRepeated realm_override_propertie = 3 [default = OVERRIDE];
  bool has_realm_override_propertie() const;
  private:
  bool _internal_has_realm_override_propertie() const;
  public:
  void clear_realm_override_propertie();
  ::google::protobuf::RealmOverrideRepeated realm_override_propertie() const;
  void set_realm_override_propertie(::google::protobuf::RealmOverrideRepeated value);
  private:
  ::google::protobuf::RealmOverrideRepeated _internal_realm_override_propertie() const;
  void _internal_set_realm_override_propertie(::google::protobuf::RealmOverrideRepeated value);
  public:

  // @@protoc_insertion_point(class_scope:google.protobuf.SwiftFieldOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool realm_indexed_propertie_;
  bool realm_primary_key_;
  int realm_override_propertie_;
  friend struct ::TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
};
// -------------------------------------------------------------------

class SwiftEnumOptions PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:google.protobuf.SwiftEnumOptions) */ {
 public:
  inline SwiftEnumOptions() : SwiftEnumOptions(nullptr) {}
  virtual ~SwiftEnumOptions();

  SwiftEnumOptions(const SwiftEnumOptions& from);
  SwiftEnumOptions(SwiftEnumOptions&& from) noexcept
    : SwiftEnumOptions() {
    *this = ::std::move(from);
  }

  inline SwiftEnumOptions& operator=(const SwiftEnumOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SwiftEnumOptions& operator=(SwiftEnumOptions&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SwiftEnumOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SwiftEnumOptions* internal_default_instance() {
    return reinterpret_cast<const SwiftEnumOptions*>(
               &_SwiftEnumOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SwiftEnumOptions& a, SwiftEnumOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(SwiftEnumOptions* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SwiftEnumOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SwiftEnumOptions* New() const final {
    return CreateMaybeMessage<SwiftEnumOptions>(nullptr);
  }

  SwiftEnumOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SwiftEnumOptions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SwiftEnumOptions& from);
  void MergeFrom(const SwiftEnumOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SwiftEnumOptions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "google.protobuf.SwiftEnumOptions";
  }
  protected:
  explicit SwiftEnumOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto);
    return ::descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGenerateErrorTypeFieldNumber = 1,
    kGenerateReactFieldNumber = 2,
    kGenerateRealmObjectFieldNumber = 3,
  };
  // optional bool generate_error_type = 1 [default = false];
  bool has_generate_error_type() const;
  private:
  bool _internal_has_generate_error_type() const;
  public:
  void clear_generate_error_type();
  bool generate_error_type() const;
  void set_generate_error_type(bool value);
  private:
  bool _internal_generate_error_type() const;
  void _internal_set_generate_error_type(bool value);
  public:

  // optional bool generate_react = 2 [default = false];
  bool has_generate_react() const;
  private:
  bool _internal_has_generate_react() const;
  public:
  void clear_generate_react();
  bool generate_react() const;
  void set_generate_react(bool value);
  private:
  bool _internal_generate_react() const;
  void _internal_set_generate_react(bool value);
  public:

  // optional bool generate_realm_object = 3 [default = false];
  bool has_generate_realm_object() const;
  private:
  bool _internal_has_generate_realm_object() const;
  public:
  void clear_generate_realm_object();
  bool generate_realm_object() const;
  void set_generate_realm_object(bool value);
  private:
  bool _internal_generate_realm_object() const;
  void _internal_set_generate_realm_object(bool value);
  public:

  // @@protoc_insertion_point(class_scope:google.protobuf.SwiftEnumOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool generate_error_type_;
  bool generate_react_;
  bool generate_realm_object_;
  friend struct ::TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
};
// ===================================================================

static const int kSwiftFileOptionsFieldNumber = 5100987;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftFileOptions >, 11, false >
  swift_file_options;
static const int kSwiftFieldOptionsFieldNumber = 5100986;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftFieldOptions >, 11, false >
  swift_field_options;
static const int kSwiftMessageOptionsFieldNumber = 5100985;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftMessageOptions >, 11, false >
  swift_message_options;
static const int kSwiftEnumOptionsFieldNumber = 5100984;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftEnumOptions >, 11, false >
  swift_enum_options;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LinkedObject

// required string fieldName = 1;
inline bool LinkedObject::_internal_has_fieldname() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LinkedObject::has_fieldname() const {
  return _internal_has_fieldname();
}
inline void LinkedObject::clear_fieldname() {
  fieldname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LinkedObject::fieldname() const {
  // @@protoc_insertion_point(field_get:google.protobuf.LinkedObject.fieldName)
  return _internal_fieldname();
}
inline void LinkedObject::set_fieldname(const std::string& value) {
  _internal_set_fieldname(value);
  // @@protoc_insertion_point(field_set:google.protobuf.LinkedObject.fieldName)
}
inline std::string* LinkedObject::mutable_fieldname() {
  // @@protoc_insertion_point(field_mutable:google.protobuf.LinkedObject.fieldName)
  return _internal_mutable_fieldname();
}
inline const std::string& LinkedObject::_internal_fieldname() const {
  return fieldname_.Get();
}
inline void LinkedObject::_internal_set_fieldname(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  fieldname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LinkedObject::set_fieldname(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  fieldname_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.LinkedObject.fieldName)
}
inline void LinkedObject::set_fieldname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  fieldname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.protobuf.LinkedObject.fieldName)
}
inline void LinkedObject::set_fieldname(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  fieldname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.LinkedObject.fieldName)
}
inline std::string* LinkedObject::_internal_mutable_fieldname() {
  _has_bits_[0] |= 0x00000001u;
  return fieldname_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LinkedObject::release_fieldname() {
  // @@protoc_insertion_point(field_release:google.protobuf.LinkedObject.fieldName)
  if (!_internal_has_fieldname()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return fieldname_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LinkedObject::set_allocated_fieldname(std::string* fieldname) {
  if (fieldname != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  fieldname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fieldname,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.LinkedObject.fieldName)
}

// required string fromType = 2;
inline bool LinkedObject::_internal_has_fromtype() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LinkedObject::has_fromtype() const {
  return _internal_has_fromtype();
}
inline void LinkedObject::clear_fromtype() {
  fromtype_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& LinkedObject::fromtype() const {
  // @@protoc_insertion_point(field_get:google.protobuf.LinkedObject.fromType)
  return _internal_fromtype();
}
inline void LinkedObject::set_fromtype(const std::string& value) {
  _internal_set_fromtype(value);
  // @@protoc_insertion_point(field_set:google.protobuf.LinkedObject.fromType)
}
inline std::string* LinkedObject::mutable_fromtype() {
  // @@protoc_insertion_point(field_mutable:google.protobuf.LinkedObject.fromType)
  return _internal_mutable_fromtype();
}
inline const std::string& LinkedObject::_internal_fromtype() const {
  return fromtype_.Get();
}
inline void LinkedObject::_internal_set_fromtype(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  fromtype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LinkedObject::set_fromtype(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  fromtype_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.LinkedObject.fromType)
}
inline void LinkedObject::set_fromtype(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  fromtype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.protobuf.LinkedObject.fromType)
}
inline void LinkedObject::set_fromtype(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  fromtype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.LinkedObject.fromType)
}
inline std::string* LinkedObject::_internal_mutable_fromtype() {
  _has_bits_[0] |= 0x00000002u;
  return fromtype_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LinkedObject::release_fromtype() {
  // @@protoc_insertion_point(field_release:google.protobuf.LinkedObject.fromType)
  if (!_internal_has_fromtype()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return fromtype_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LinkedObject::set_allocated_fromtype(std::string* fromtype) {
  if (fromtype != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  fromtype_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fromtype,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.LinkedObject.fromType)
}

// required string propertyName = 3;
inline bool LinkedObject::_internal_has_propertyname() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool LinkedObject::has_propertyname() const {
  return _internal_has_propertyname();
}
inline void LinkedObject::clear_propertyname() {
  propertyname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& LinkedObject::propertyname() const {
  // @@protoc_insertion_point(field_get:google.protobuf.LinkedObject.propertyName)
  return _internal_propertyname();
}
inline void LinkedObject::set_propertyname(const std::string& value) {
  _internal_set_propertyname(value);
  // @@protoc_insertion_point(field_set:google.protobuf.LinkedObject.propertyName)
}
inline std::string* LinkedObject::mutable_propertyname() {
  // @@protoc_insertion_point(field_mutable:google.protobuf.LinkedObject.propertyName)
  return _internal_mutable_propertyname();
}
inline const std::string& LinkedObject::_internal_propertyname() const {
  return propertyname_.Get();
}
inline void LinkedObject::_internal_set_propertyname(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  propertyname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LinkedObject::set_propertyname(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  propertyname_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.LinkedObject.propertyName)
}
inline void LinkedObject::set_propertyname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  propertyname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.protobuf.LinkedObject.propertyName)
}
inline void LinkedObject::set_propertyname(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  propertyname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.LinkedObject.propertyName)
}
inline std::string* LinkedObject::_internal_mutable_propertyname() {
  _has_bits_[0] |= 0x00000004u;
  return propertyname_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LinkedObject::release_propertyname() {
  // @@protoc_insertion_point(field_release:google.protobuf.LinkedObject.propertyName)
  if (!_internal_has_propertyname()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return propertyname_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LinkedObject::set_allocated_propertyname(std::string* propertyname) {
  if (propertyname != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  propertyname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), propertyname,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.LinkedObject.propertyName)
}

// -------------------------------------------------------------------

// SwiftFileOptions

// optional string class_prefix = 1;
inline bool SwiftFileOptions::_internal_has_class_prefix() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SwiftFileOptions::has_class_prefix() const {
  return _internal_has_class_prefix();
}
inline void SwiftFileOptions::clear_class_prefix() {
  class_prefix_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SwiftFileOptions::class_prefix() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFileOptions.class_prefix)
  return _internal_class_prefix();
}
inline void SwiftFileOptions::set_class_prefix(const std::string& value) {
  _internal_set_class_prefix(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFileOptions.class_prefix)
}
inline std::string* SwiftFileOptions::mutable_class_prefix() {
  // @@protoc_insertion_point(field_mutable:google.protobuf.SwiftFileOptions.class_prefix)
  return _internal_mutable_class_prefix();
}
inline const std::string& SwiftFileOptions::_internal_class_prefix() const {
  return class_prefix_.Get();
}
inline void SwiftFileOptions::_internal_set_class_prefix(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  class_prefix_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SwiftFileOptions::set_class_prefix(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  class_prefix_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.SwiftFileOptions.class_prefix)
}
inline void SwiftFileOptions::set_class_prefix(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  class_prefix_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.protobuf.SwiftFileOptions.class_prefix)
}
inline void SwiftFileOptions::set_class_prefix(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  class_prefix_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.SwiftFileOptions.class_prefix)
}
inline std::string* SwiftFileOptions::_internal_mutable_class_prefix() {
  _has_bits_[0] |= 0x00000001u;
  return class_prefix_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SwiftFileOptions::release_class_prefix() {
  // @@protoc_insertion_point(field_release:google.protobuf.SwiftFileOptions.class_prefix)
  if (!_internal_has_class_prefix()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return class_prefix_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SwiftFileOptions::set_allocated_class_prefix(std::string* class_prefix) {
  if (class_prefix != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  class_prefix_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), class_prefix,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.SwiftFileOptions.class_prefix)
}

// optional .google.protobuf.AccessControl entities_access_control = 2 [default = PublicEntities];
inline bool SwiftFileOptions::_internal_has_entities_access_control() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool SwiftFileOptions::has_entities_access_control() const {
  return _internal_has_entities_access_control();
}
inline void SwiftFileOptions::clear_entities_access_control() {
  entities_access_control_ = 1;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::AccessControl SwiftFileOptions::_internal_entities_access_control() const {
  return static_cast< ::google::protobuf::AccessControl >(entities_access_control_);
}
inline ::google::protobuf::AccessControl SwiftFileOptions::entities_access_control() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFileOptions.entities_access_control)
  return _internal_entities_access_control();
}
inline void SwiftFileOptions::_internal_set_entities_access_control(::google::protobuf::AccessControl value) {
  assert(::google::protobuf::AccessControl_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  entities_access_control_ = value;
}
inline void SwiftFileOptions::set_entities_access_control(::google::protobuf::AccessControl value) {
  _internal_set_entities_access_control(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFileOptions.entities_access_control)
}

// optional bool compile_for_framework = 3 [default = true];
inline bool SwiftFileOptions::_internal_has_compile_for_framework() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool SwiftFileOptions::has_compile_for_framework() const {
  return _internal_has_compile_for_framework();
}
inline void SwiftFileOptions::clear_compile_for_framework() {
  compile_for_framework_ = true;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool SwiftFileOptions::_internal_compile_for_framework() const {
  return compile_for_framework_;
}
inline bool SwiftFileOptions::compile_for_framework() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFileOptions.compile_for_framework)
  return _internal_compile_for_framework();
}
inline void SwiftFileOptions::_internal_set_compile_for_framework(bool value) {
  _has_bits_[0] |= 0x00000020u;
  compile_for_framework_ = value;
}
inline void SwiftFileOptions::set_compile_for_framework(bool value) {
  _internal_set_compile_for_framework(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFileOptions.compile_for_framework)
}

// optional bool generate_struct = 4 [default = false];
inline bool SwiftFileOptions::_internal_has_generate_struct() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SwiftFileOptions::has_generate_struct() const {
  return _internal_has_generate_struct();
}
inline void SwiftFileOptions::clear_generate_struct() {
  generate_struct_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool SwiftFileOptions::_internal_generate_struct() const {
  return generate_struct_;
}
inline bool SwiftFileOptions::generate_struct() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFileOptions.generate_struct)
  return _internal_generate_struct();
}
inline void SwiftFileOptions::_internal_set_generate_struct(bool value) {
  _has_bits_[0] |= 0x00000002u;
  generate_struct_ = value;
}
inline void SwiftFileOptions::set_generate_struct(bool value) {
  _internal_set_generate_struct(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFileOptions.generate_struct)
}

// optional bool generate_realm_objects = 5 [default = false];
inline bool SwiftFileOptions::_internal_has_generate_realm_objects() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SwiftFileOptions::has_generate_realm_objects() const {
  return _internal_has_generate_realm_objects();
}
inline void SwiftFileOptions::clear_generate_realm_objects() {
  generate_realm_objects_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool SwiftFileOptions::_internal_generate_realm_objects() const {
  return generate_realm_objects_;
}
inline bool SwiftFileOptions::generate_realm_objects() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFileOptions.generate_realm_objects)
  return _internal_generate_realm_objects();
}
inline void SwiftFileOptions::_internal_set_generate_realm_objects(bool value) {
  _has_bits_[0] |= 0x00000004u;
  generate_realm_objects_ = value;
}
inline void SwiftFileOptions::set_generate_realm_objects(bool value) {
  _internal_set_generate_realm_objects(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFileOptions.generate_realm_objects)
}

// optional bool generate_react = 6 [default = false];
inline bool SwiftFileOptions::_internal_has_generate_react() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool SwiftFileOptions::has_generate_react() const {
  return _internal_has_generate_react();
}
inline void SwiftFileOptions::clear_generate_react() {
  generate_react_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool SwiftFileOptions::_internal_generate_react() const {
  return generate_react_;
}
inline bool SwiftFileOptions::generate_react() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFileOptions.generate_react)
  return _internal_generate_react();
}
inline void SwiftFileOptions::_internal_set_generate_react(bool value) {
  _has_bits_[0] |= 0x00000008u;
  generate_react_ = value;
}
inline void SwiftFileOptions::set_generate_react(bool value) {
  _internal_set_generate_react(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFileOptions.generate_react)
}

// -------------------------------------------------------------------

// SwiftMessageOptions

// optional bool generate_error_type = 1 [default = false];
inline bool SwiftMessageOptions::_internal_has_generate_error_type() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SwiftMessageOptions::has_generate_error_type() const {
  return _internal_has_generate_error_type();
}
inline void SwiftMessageOptions::clear_generate_error_type() {
  generate_error_type_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool SwiftMessageOptions::_internal_generate_error_type() const {
  return generate_error_type_;
}
inline bool SwiftMessageOptions::generate_error_type() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftMessageOptions.generate_error_type)
  return _internal_generate_error_type();
}
inline void SwiftMessageOptions::_internal_set_generate_error_type(bool value) {
  _has_bits_[0] |= 0x00000002u;
  generate_error_type_ = value;
}
inline void SwiftMessageOptions::set_generate_error_type(bool value) {
  _internal_set_generate_error_type(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftMessageOptions.generate_error_type)
}

// optional bool generate_realm_object = 2 [default = false];
inline bool SwiftMessageOptions::_internal_has_generate_realm_object() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SwiftMessageOptions::has_generate_realm_object() const {
  return _internal_has_generate_realm_object();
}
inline void SwiftMessageOptions::clear_generate_realm_object() {
  generate_realm_object_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool SwiftMessageOptions::_internal_generate_realm_object() const {
  return generate_realm_object_;
}
inline bool SwiftMessageOptions::generate_realm_object() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftMessageOptions.generate_realm_object)
  return _internal_generate_realm_object();
}
inline void SwiftMessageOptions::_internal_set_generate_realm_object(bool value) {
  _has_bits_[0] |= 0x00000004u;
  generate_realm_object_ = value;
}
inline void SwiftMessageOptions::set_generate_realm_object(bool value) {
  _internal_set_generate_realm_object(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftMessageOptions.generate_realm_object)
}

// optional bool generate_react = 3 [default = false];
inline bool SwiftMessageOptions::_internal_has_generate_react() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool SwiftMessageOptions::has_generate_react() const {
  return _internal_has_generate_react();
}
inline void SwiftMessageOptions::clear_generate_react() {
  generate_react_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool SwiftMessageOptions::_internal_generate_react() const {
  return generate_react_;
}
inline bool SwiftMessageOptions::generate_react() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftMessageOptions.generate_react)
  return _internal_generate_react();
}
inline void SwiftMessageOptions::_internal_set_generate_react(bool value) {
  _has_bits_[0] |= 0x00000008u;
  generate_react_ = value;
}
inline void SwiftMessageOptions::set_generate_react(bool value) {
  _internal_set_generate_react(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftMessageOptions.generate_react)
}

// optional string additional_class_name = 4;
inline bool SwiftMessageOptions::_internal_has_additional_class_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SwiftMessageOptions::has_additional_class_name() const {
  return _internal_has_additional_class_name();
}
inline void SwiftMessageOptions::clear_additional_class_name() {
  additional_class_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SwiftMessageOptions::additional_class_name() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftMessageOptions.additional_class_name)
  return _internal_additional_class_name();
}
inline void SwiftMessageOptions::set_additional_class_name(const std::string& value) {
  _internal_set_additional_class_name(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftMessageOptions.additional_class_name)
}
inline std::string* SwiftMessageOptions::mutable_additional_class_name() {
  // @@protoc_insertion_point(field_mutable:google.protobuf.SwiftMessageOptions.additional_class_name)
  return _internal_mutable_additional_class_name();
}
inline const std::string& SwiftMessageOptions::_internal_additional_class_name() const {
  return additional_class_name_.Get();
}
inline void SwiftMessageOptions::_internal_set_additional_class_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  additional_class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SwiftMessageOptions::set_additional_class_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  additional_class_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.SwiftMessageOptions.additional_class_name)
}
inline void SwiftMessageOptions::set_additional_class_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  additional_class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:google.protobuf.SwiftMessageOptions.additional_class_name)
}
inline void SwiftMessageOptions::set_additional_class_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  additional_class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.SwiftMessageOptions.additional_class_name)
}
inline std::string* SwiftMessageOptions::_internal_mutable_additional_class_name() {
  _has_bits_[0] |= 0x00000001u;
  return additional_class_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SwiftMessageOptions::release_additional_class_name() {
  // @@protoc_insertion_point(field_release:google.protobuf.SwiftMessageOptions.additional_class_name)
  if (!_internal_has_additional_class_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return additional_class_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SwiftMessageOptions::set_allocated_additional_class_name(std::string* additional_class_name) {
  if (additional_class_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  additional_class_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), additional_class_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.SwiftMessageOptions.additional_class_name)
}

// repeated .google.protobuf.LinkedObject linkedObjects = 5;
inline int SwiftMessageOptions::_internal_linkedobjects_size() const {
  return linkedobjects_.size();
}
inline int SwiftMessageOptions::linkedobjects_size() const {
  return _internal_linkedobjects_size();
}
inline void SwiftMessageOptions::clear_linkedobjects() {
  linkedobjects_.Clear();
}
inline ::google::protobuf::LinkedObject* SwiftMessageOptions::mutable_linkedobjects(int index) {
  // @@protoc_insertion_point(field_mutable:google.protobuf.SwiftMessageOptions.linkedObjects)
  return linkedobjects_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::protobuf::LinkedObject >*
SwiftMessageOptions::mutable_linkedobjects() {
  // @@protoc_insertion_point(field_mutable_list:google.protobuf.SwiftMessageOptions.linkedObjects)
  return &linkedobjects_;
}
inline const ::google::protobuf::LinkedObject& SwiftMessageOptions::_internal_linkedobjects(int index) const {
  return linkedobjects_.Get(index);
}
inline const ::google::protobuf::LinkedObject& SwiftMessageOptions::linkedobjects(int index) const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftMessageOptions.linkedObjects)
  return _internal_linkedobjects(index);
}
inline ::google::protobuf::LinkedObject* SwiftMessageOptions::_internal_add_linkedobjects() {
  return linkedobjects_.Add();
}
inline ::google::protobuf::LinkedObject* SwiftMessageOptions::add_linkedobjects() {
  // @@protoc_insertion_point(field_add:google.protobuf.SwiftMessageOptions.linkedObjects)
  return _internal_add_linkedobjects();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::google::protobuf::LinkedObject >&
SwiftMessageOptions::linkedobjects() const {
  // @@protoc_insertion_point(field_list:google.protobuf.SwiftMessageOptions.linkedObjects)
  return linkedobjects_;
}

// -------------------------------------------------------------------

// SwiftFieldOptions

// optional bool realm_indexed_propertie = 1 [default = false];
inline bool SwiftFieldOptions::_internal_has_realm_indexed_propertie() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SwiftFieldOptions::has_realm_indexed_propertie() const {
  return _internal_has_realm_indexed_propertie();
}
inline void SwiftFieldOptions::clear_realm_indexed_propertie() {
  realm_indexed_propertie_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool SwiftFieldOptions::_internal_realm_indexed_propertie() const {
  return realm_indexed_propertie_;
}
inline bool SwiftFieldOptions::realm_indexed_propertie() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFieldOptions.realm_indexed_propertie)
  return _internal_realm_indexed_propertie();
}
inline void SwiftFieldOptions::_internal_set_realm_indexed_propertie(bool value) {
  _has_bits_[0] |= 0x00000001u;
  realm_indexed_propertie_ = value;
}
inline void SwiftFieldOptions::set_realm_indexed_propertie(bool value) {
  _internal_set_realm_indexed_propertie(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFieldOptions.realm_indexed_propertie)
}

// optional bool realm_primary_key = 2 [default = false];
inline bool SwiftFieldOptions::_internal_has_realm_primary_key() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SwiftFieldOptions::has_realm_primary_key() const {
  return _internal_has_realm_primary_key();
}
inline void SwiftFieldOptions::clear_realm_primary_key() {
  realm_primary_key_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool SwiftFieldOptions::_internal_realm_primary_key() const {
  return realm_primary_key_;
}
inline bool SwiftFieldOptions::realm_primary_key() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFieldOptions.realm_primary_key)
  return _internal_realm_primary_key();
}
inline void SwiftFieldOptions::_internal_set_realm_primary_key(bool value) {
  _has_bits_[0] |= 0x00000002u;
  realm_primary_key_ = value;
}
inline void SwiftFieldOptions::set_realm_primary_key(bool value) {
  _internal_set_realm_primary_key(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFieldOptions.realm_primary_key)
}

// optional .google.protobuf.RealmOverrideRepeated realm_override_propertie = 3 [default = OVERRIDE];
inline bool SwiftFieldOptions::_internal_has_realm_override_propertie() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SwiftFieldOptions::has_realm_override_propertie() const {
  return _internal_has_realm_override_propertie();
}
inline void SwiftFieldOptions::clear_realm_override_propertie() {
  realm_override_propertie_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::RealmOverrideRepeated SwiftFieldOptions::_internal_realm_override_propertie() const {
  return static_cast< ::google::protobuf::RealmOverrideRepeated >(realm_override_propertie_);
}
inline ::google::protobuf::RealmOverrideRepeated SwiftFieldOptions::realm_override_propertie() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftFieldOptions.realm_override_propertie)
  return _internal_realm_override_propertie();
}
inline void SwiftFieldOptions::_internal_set_realm_override_propertie(::google::protobuf::RealmOverrideRepeated value) {
  assert(::google::protobuf::RealmOverrideRepeated_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  realm_override_propertie_ = value;
}
inline void SwiftFieldOptions::set_realm_override_propertie(::google::protobuf::RealmOverrideRepeated value) {
  _internal_set_realm_override_propertie(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftFieldOptions.realm_override_propertie)
}

// -------------------------------------------------------------------

// SwiftEnumOptions

// optional bool generate_error_type = 1 [default = false];
inline bool SwiftEnumOptions::_internal_has_generate_error_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SwiftEnumOptions::has_generate_error_type() const {
  return _internal_has_generate_error_type();
}
inline void SwiftEnumOptions::clear_generate_error_type() {
  generate_error_type_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool SwiftEnumOptions::_internal_generate_error_type() const {
  return generate_error_type_;
}
inline bool SwiftEnumOptions::generate_error_type() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftEnumOptions.generate_error_type)
  return _internal_generate_error_type();
}
inline void SwiftEnumOptions::_internal_set_generate_error_type(bool value) {
  _has_bits_[0] |= 0x00000001u;
  generate_error_type_ = value;
}
inline void SwiftEnumOptions::set_generate_error_type(bool value) {
  _internal_set_generate_error_type(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftEnumOptions.generate_error_type)
}

// optional bool generate_react = 2 [default = false];
inline bool SwiftEnumOptions::_internal_has_generate_react() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SwiftEnumOptions::has_generate_react() const {
  return _internal_has_generate_react();
}
inline void SwiftEnumOptions::clear_generate_react() {
  generate_react_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool SwiftEnumOptions::_internal_generate_react() const {
  return generate_react_;
}
inline bool SwiftEnumOptions::generate_react() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftEnumOptions.generate_react)
  return _internal_generate_react();
}
inline void SwiftEnumOptions::_internal_set_generate_react(bool value) {
  _has_bits_[0] |= 0x00000002u;
  generate_react_ = value;
}
inline void SwiftEnumOptions::set_generate_react(bool value) {
  _internal_set_generate_react(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftEnumOptions.generate_react)
}

// optional bool generate_realm_object = 3 [default = false];
inline bool SwiftEnumOptions::_internal_has_generate_realm_object() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SwiftEnumOptions::has_generate_realm_object() const {
  return _internal_has_generate_realm_object();
}
inline void SwiftEnumOptions::clear_generate_realm_object() {
  generate_realm_object_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool SwiftEnumOptions::_internal_generate_realm_object() const {
  return generate_realm_object_;
}
inline bool SwiftEnumOptions::generate_realm_object() const {
  // @@protoc_insertion_point(field_get:google.protobuf.SwiftEnumOptions.generate_realm_object)
  return _internal_generate_realm_object();
}
inline void SwiftEnumOptions::_internal_set_generate_realm_object(bool value) {
  _has_bits_[0] |= 0x00000004u;
  generate_realm_object_ = value;
}
inline void SwiftEnumOptions::set_generate_realm_object(bool value) {
  _internal_set_generate_realm_object(value);
  // @@protoc_insertion_point(field_set:google.protobuf.SwiftEnumOptions.generate_realm_object)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::google::protobuf::AccessControl> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::protobuf::AccessControl>() {
  return ::google::protobuf::AccessControl_descriptor();
}
template <> struct is_proto_enum< ::google::protobuf::RealmOverrideRepeated> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::google::protobuf::RealmOverrideRepeated>() {
  return ::google::protobuf::RealmOverrideRepeated_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_google_2fprotobuf_2fswift_2ddescriptor_2eproto
