// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/swift-descriptor.proto

#include "google/protobuf/swift-descriptor.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fswift_2ddescriptor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fswift_2ddescriptor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SwiftEnumOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fswift_2ddescriptor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SwiftFieldOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fswift_2ddescriptor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SwiftFileOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fswift_2ddescriptor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SwiftMessageOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto;
namespace google {
namespace protobuf {
class LinkedObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LinkedObject> _instance;
} _LinkedObject_default_instance_;
class SwiftFileOptionsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SwiftFileOptions> _instance;
} _SwiftFileOptions_default_instance_;
class SwiftMessageOptionsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SwiftMessageOptions> _instance;
} _SwiftMessageOptions_default_instance_;
class SwiftFieldOptionsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SwiftFieldOptions> _instance;
} _SwiftFieldOptions_default_instance_;
class SwiftEnumOptionsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SwiftEnumOptions> _instance;
} _SwiftEnumOptions_default_instance_;
}  // namespace protobuf
}  // namespace google
static void InitDefaultsscc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::_LinkedObject_default_instance_;
    new (ptr) ::google::protobuf::LinkedObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::LinkedObject::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto}, {}};

static void InitDefaultsscc_info_SwiftEnumOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::_SwiftEnumOptions_default_instance_;
    new (ptr) ::google::protobuf::SwiftEnumOptions();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::SwiftEnumOptions::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SwiftEnumOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SwiftEnumOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto}, {}};

static void InitDefaultsscc_info_SwiftFieldOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::_SwiftFieldOptions_default_instance_;
    new (ptr) ::google::protobuf::SwiftFieldOptions();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::SwiftFieldOptions::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SwiftFieldOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SwiftFieldOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto}, {}};

static void InitDefaultsscc_info_SwiftFileOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::_SwiftFileOptions_default_instance_;
    new (ptr) ::google::protobuf::SwiftFileOptions();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::SwiftFileOptions::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SwiftFileOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SwiftFileOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto}, {}};

static void InitDefaultsscc_info_SwiftMessageOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::_SwiftMessageOptions_default_instance_;
    new (ptr) ::google::protobuf::SwiftMessageOptions();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::SwiftMessageOptions::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SwiftMessageOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SwiftMessageOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto}, {
      &scc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_google_2fprotobuf_2fswift_2ddescriptor_2eproto[5];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_google_2fprotobuf_2fswift_2ddescriptor_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_google_2fprotobuf_2fswift_2ddescriptor_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::google::protobuf::LinkedObject, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::LinkedObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::google::protobuf::LinkedObject, fieldname_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::LinkedObject, fromtype_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::LinkedObject, propertyname_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, class_prefix_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, entities_access_control_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, compile_for_framework_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, generate_struct_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, generate_realm_objects_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFileOptions, generate_react_),
  0,
  4,
  5,
  1,
  2,
  3,
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftMessageOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftMessageOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftMessageOptions, generate_error_type_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftMessageOptions, generate_realm_object_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftMessageOptions, generate_react_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftMessageOptions, additional_class_name_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftMessageOptions, linkedobjects_),
  1,
  2,
  3,
  0,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFieldOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFieldOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFieldOptions, realm_indexed_propertie_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFieldOptions, realm_primary_key_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftFieldOptions, realm_override_propertie_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftEnumOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftEnumOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftEnumOptions, generate_error_type_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftEnumOptions, generate_react_),
  PROTOBUF_FIELD_OFFSET(::google::protobuf::SwiftEnumOptions, generate_realm_object_),
  0,
  1,
  2,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::google::protobuf::LinkedObject)},
  { 11, 22, sizeof(::google::protobuf::SwiftFileOptions)},
  { 28, 38, sizeof(::google::protobuf::SwiftMessageOptions)},
  { 43, 51, sizeof(::google::protobuf::SwiftFieldOptions)},
  { 54, 62, sizeof(::google::protobuf::SwiftEnumOptions)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::google::protobuf::_LinkedObject_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::google::protobuf::_SwiftFileOptions_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::google::protobuf::_SwiftMessageOptions_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::google::protobuf::_SwiftFieldOptions_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::google::protobuf::_SwiftEnumOptions_default_instance_),
};

const char descriptor_table_protodef_google_2fprotobuf_2fswift_2ddescriptor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&google/protobuf/swift-descriptor.proto"
  "\022\017google.protobuf\032 google/protobuf/descr"
  "iptor.proto\"I\n\014LinkedObject\022\021\n\tfieldName"
  "\030\001 \002(\t\022\020\n\010fromType\030\002 \002(\t\022\024\n\014propertyName"
  "\030\003 \002(\t\"\204\002\n\020SwiftFileOptions\022\024\n\014class_pre"
  "fix\030\001 \001(\t\022O\n\027entities_access_control\030\002 \001"
  "(\0162\036.google.protobuf.AccessControl:\016Publ"
  "icEntities\022#\n\025compile_for_framework\030\003 \001("
  "\010:\004true\022\036\n\017generate_struct\030\004 \001(\010:\005false\022"
  "%\n\026generate_realm_objects\030\005 \001(\010:\005false\022\035"
  "\n\016generate_react\030\006 \001(\010:\005false\"\323\001\n\023SwiftM"
  "essageOptions\022\"\n\023generate_error_type\030\001 \001"
  "(\010:\005false\022$\n\025generate_realm_object\030\002 \001(\010"
  ":\005false\022\035\n\016generate_react\030\003 \001(\010:\005false\022\035"
  "\n\025additional_class_name\030\004 \001(\t\0224\n\rlinkedO"
  "bjects\030\005 \003(\0132\035.google.protobuf.LinkedObj"
  "ect\"\261\001\n\021SwiftFieldOptions\022&\n\027realm_index"
  "ed_propertie\030\001 \001(\010:\005false\022 \n\021realm_prima"
  "ry_key\030\002 \001(\010:\005false\022R\n\030realm_override_pr"
  "opertie\030\003 \001(\0162&.google.protobuf.RealmOve"
  "rrideRepeated:\010OVERRIDE\"{\n\020SwiftEnumOpti"
  "ons\022\"\n\023generate_error_type\030\001 \001(\010:\005false\022"
  "\035\n\016generate_react\030\002 \001(\010:\005false\022$\n\025genera"
  "te_realm_object\030\003 \001(\010:\005false*9\n\rAccessCo"
  "ntrol\022\024\n\020InternalEntities\020\000\022\022\n\016PublicEnt"
  "ities\020\001*1\n\025RealmOverrideRepeated\022\014\n\010OVER"
  "RIDE\020\000\022\n\n\006APPEND\020\001:^\n\022swift_file_options"
  "\022\034.google.protobuf.FileOptions\030\273\253\267\002 \001(\0132"
  "!.google.protobuf.SwiftFileOptions:a\n\023sw"
  "ift_field_options\022\035.google.protobuf.Fiel"
  "dOptions\030\272\253\267\002 \001(\0132\".google.protobuf.Swif"
  "tFieldOptions:g\n\025swift_message_options\022\037"
  ".google.protobuf.MessageOptions\030\271\253\267\002 \001(\013"
  "2$.google.protobuf.SwiftMessageOptions:^"
  "\n\022swift_enum_options\022\034.google.protobuf.E"
  "numOptions\030\270\253\267\002 \001(\0132!.google.protobuf.Sw"
  "iftEnumOptionsB\016\332\333\272\023\002\030\000\332\333\272\023\002\020\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto_sccs[5] = {
  &scc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base,
  &scc_info_SwiftEnumOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base,
  &scc_info_SwiftFieldOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base,
  &scc_info_SwiftFileOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base,
  &scc_info_SwiftMessageOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto = {
  false, false, descriptor_table_protodef_google_2fprotobuf_2fswift_2ddescriptor_2eproto, "google/protobuf/swift-descriptor.proto", 1470,
  &descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto_once, descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto_sccs, descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto_deps, 5, 1,
  schemas, file_default_instances, TableStruct_google_2fprotobuf_2fswift_2ddescriptor_2eproto::offsets,
  file_level_metadata_google_2fprotobuf_2fswift_2ddescriptor_2eproto, 5, file_level_enum_descriptors_google_2fprotobuf_2fswift_2ddescriptor_2eproto, file_level_service_descriptors_google_2fprotobuf_2fswift_2ddescriptor_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_google_2fprotobuf_2fswift_2ddescriptor_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto)), true);
namespace google {
namespace protobuf {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccessControl_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto);
  return file_level_enum_descriptors_google_2fprotobuf_2fswift_2ddescriptor_2eproto[0];
}
bool AccessControl_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RealmOverrideRepeated_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_google_2fprotobuf_2fswift_2ddescriptor_2eproto);
  return file_level_enum_descriptors_google_2fprotobuf_2fswift_2ddescriptor_2eproto[1];
}
bool RealmOverrideRepeated_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void LinkedObject::InitAsDefaultInstance() {
}
class LinkedObject::_Internal {
 public:
  using HasBits = decltype(std::declval<LinkedObject>()._has_bits_);
  static void set_has_fieldname(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_fromtype(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_propertyname(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

LinkedObject::LinkedObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.protobuf.LinkedObject)
}
LinkedObject::LinkedObject(const LinkedObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  fieldname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_fieldname()) {
    fieldname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_fieldname(),
      GetArena());
  }
  fromtype_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_fromtype()) {
    fromtype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_fromtype(),
      GetArena());
  }
  propertyname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_propertyname()) {
    propertyname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_propertyname(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:google.protobuf.LinkedObject)
}

void LinkedObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  fieldname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  fromtype_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  propertyname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

LinkedObject::~LinkedObject() {
  // @@protoc_insertion_point(destructor:google.protobuf.LinkedObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LinkedObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  fieldname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  fromtype_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  propertyname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void LinkedObject::ArenaDtor(void* object) {
  LinkedObject* _this = reinterpret_cast< LinkedObject* >(object);
  (void)_this;
}
void LinkedObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LinkedObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LinkedObject& LinkedObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LinkedObject_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  return *internal_default_instance();
}


void LinkedObject::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.LinkedObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      fieldname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      fromtype_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      propertyname_.ClearNonDefaultToEmpty();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LinkedObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required string fieldName = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_fieldname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "google.protobuf.LinkedObject.fieldName");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string fromType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_fromtype();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "google.protobuf.LinkedObject.fromType");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string propertyName = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_propertyname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "google.protobuf.LinkedObject.propertyName");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LinkedObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.LinkedObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string fieldName = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_fieldname().data(), static_cast<int>(this->_internal_fieldname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "google.protobuf.LinkedObject.fieldName");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_fieldname(), target);
  }

  // required string fromType = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_fromtype().data(), static_cast<int>(this->_internal_fromtype().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "google.protobuf.LinkedObject.fromType");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fromtype(), target);
  }

  // required string propertyName = 3;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_propertyname().data(), static_cast<int>(this->_internal_propertyname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "google.protobuf.LinkedObject.propertyName");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_propertyname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.LinkedObject)
  return target;
}

size_t LinkedObject::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:google.protobuf.LinkedObject)
  size_t total_size = 0;

  if (_internal_has_fieldname()) {
    // required string fieldName = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fieldname());
  }

  if (_internal_has_fromtype()) {
    // required string fromType = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fromtype());
  }

  if (_internal_has_propertyname()) {
    // required string propertyName = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_propertyname());
  }

  return total_size;
}
size_t LinkedObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.LinkedObject)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string fieldName = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fieldname());

    // required string fromType = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fromtype());

    // required string propertyName = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_propertyname());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LinkedObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.LinkedObject)
  GOOGLE_DCHECK_NE(&from, this);
  const LinkedObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LinkedObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.LinkedObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.LinkedObject)
    MergeFrom(*source);
  }
}

void LinkedObject::MergeFrom(const LinkedObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.LinkedObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_fieldname(from._internal_fieldname());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_fromtype(from._internal_fromtype());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_propertyname(from._internal_propertyname());
    }
  }
}

void LinkedObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.LinkedObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LinkedObject::CopyFrom(const LinkedObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.LinkedObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LinkedObject::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void LinkedObject::InternalSwap(LinkedObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  fieldname_.Swap(&other->fieldname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  fromtype_.Swap(&other->fromtype_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  propertyname_.Swap(&other->propertyname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata LinkedObject::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SwiftFileOptions::InitAsDefaultInstance() {
}
class SwiftFileOptions::_Internal {
 public:
  using HasBits = decltype(std::declval<SwiftFileOptions>()._has_bits_);
  static void set_has_class_prefix(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_entities_access_control(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_compile_for_framework(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_generate_struct(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_generate_realm_objects(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_generate_react(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

SwiftFileOptions::SwiftFileOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.protobuf.SwiftFileOptions)
}
SwiftFileOptions::SwiftFileOptions(const SwiftFileOptions& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  class_prefix_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_class_prefix()) {
    class_prefix_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_class_prefix(),
      GetArena());
  }
  ::memcpy(&generate_struct_, &from.generate_struct_,
    static_cast<size_t>(reinterpret_cast<char*>(&compile_for_framework_) -
    reinterpret_cast<char*>(&generate_struct_)) + sizeof(compile_for_framework_));
  // @@protoc_insertion_point(copy_constructor:google.protobuf.SwiftFileOptions)
}

void SwiftFileOptions::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SwiftFileOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  class_prefix_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&generate_struct_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&generate_react_) -
      reinterpret_cast<char*>(&generate_struct_)) + sizeof(generate_react_));
  entities_access_control_ = 1;
  compile_for_framework_ = true;
}

SwiftFileOptions::~SwiftFileOptions() {
  // @@protoc_insertion_point(destructor:google.protobuf.SwiftFileOptions)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SwiftFileOptions::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  class_prefix_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SwiftFileOptions::ArenaDtor(void* object) {
  SwiftFileOptions* _this = reinterpret_cast< SwiftFileOptions* >(object);
  (void)_this;
}
void SwiftFileOptions::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SwiftFileOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SwiftFileOptions& SwiftFileOptions::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SwiftFileOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  return *internal_default_instance();
}


void SwiftFileOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.SwiftFileOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    class_prefix_.ClearNonDefaultToEmpty();
  }
  ::memset(&generate_struct_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&generate_react_) -
      reinterpret_cast<char*>(&generate_struct_)) + sizeof(generate_react_));
  if (cached_has_bits & 0x00000030u) {
    entities_access_control_ = 1;
    compile_for_framework_ = true;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SwiftFileOptions::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string class_prefix = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_class_prefix();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "google.protobuf.SwiftFileOptions.class_prefix");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .google.protobuf.AccessControl entities_access_control = 2 [default = PublicEntities];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::google::protobuf::AccessControl_IsValid(val))) {
            _internal_set_entities_access_control(static_cast<::google::protobuf::AccessControl>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // optional bool compile_for_framework = 3 [default = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_compile_for_framework(&has_bits);
          compile_for_framework_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool generate_struct = 4 [default = false];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_generate_struct(&has_bits);
          generate_struct_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool generate_realm_objects = 5 [default = false];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_generate_realm_objects(&has_bits);
          generate_realm_objects_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool generate_react = 6 [default = false];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_generate_react(&has_bits);
          generate_react_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SwiftFileOptions::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.SwiftFileOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string class_prefix = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_class_prefix().data(), static_cast<int>(this->_internal_class_prefix().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "google.protobuf.SwiftFileOptions.class_prefix");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_class_prefix(), target);
  }

  // optional .google.protobuf.AccessControl entities_access_control = 2 [default = PublicEntities];
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_entities_access_control(), target);
  }

  // optional bool compile_for_framework = 3 [default = true];
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_compile_for_framework(), target);
  }

  // optional bool generate_struct = 4 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_generate_struct(), target);
  }

  // optional bool generate_realm_objects = 5 [default = false];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_generate_realm_objects(), target);
  }

  // optional bool generate_react = 6 [default = false];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_generate_react(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.SwiftFileOptions)
  return target;
}

size_t SwiftFileOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.SwiftFileOptions)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string class_prefix = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_class_prefix());
    }

    // optional bool generate_struct = 4 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool generate_realm_objects = 5 [default = false];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

    // optional bool generate_react = 6 [default = false];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional .google.protobuf.AccessControl entities_access_control = 2 [default = PublicEntities];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_entities_access_control());
    }

    // optional bool compile_for_framework = 3 [default = true];
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 1;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SwiftFileOptions::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.SwiftFileOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const SwiftFileOptions* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SwiftFileOptions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.SwiftFileOptions)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.SwiftFileOptions)
    MergeFrom(*source);
  }
}

void SwiftFileOptions::MergeFrom(const SwiftFileOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.SwiftFileOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_class_prefix(from._internal_class_prefix());
    }
    if (cached_has_bits & 0x00000002u) {
      generate_struct_ = from.generate_struct_;
    }
    if (cached_has_bits & 0x00000004u) {
      generate_realm_objects_ = from.generate_realm_objects_;
    }
    if (cached_has_bits & 0x00000008u) {
      generate_react_ = from.generate_react_;
    }
    if (cached_has_bits & 0x00000010u) {
      entities_access_control_ = from.entities_access_control_;
    }
    if (cached_has_bits & 0x00000020u) {
      compile_for_framework_ = from.compile_for_framework_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SwiftFileOptions::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.SwiftFileOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SwiftFileOptions::CopyFrom(const SwiftFileOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.SwiftFileOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwiftFileOptions::IsInitialized() const {
  return true;
}

void SwiftFileOptions::InternalSwap(SwiftFileOptions* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  class_prefix_.Swap(&other->class_prefix_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SwiftFileOptions, generate_react_)
      + sizeof(SwiftFileOptions::generate_react_)
      - PROTOBUF_FIELD_OFFSET(SwiftFileOptions, generate_struct_)>(
          reinterpret_cast<char*>(&generate_struct_),
          reinterpret_cast<char*>(&other->generate_struct_));
  swap(entities_access_control_, other->entities_access_control_);
  swap(compile_for_framework_, other->compile_for_framework_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SwiftFileOptions::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SwiftMessageOptions::InitAsDefaultInstance() {
}
class SwiftMessageOptions::_Internal {
 public:
  using HasBits = decltype(std::declval<SwiftMessageOptions>()._has_bits_);
  static void set_has_generate_error_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_generate_realm_object(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_generate_react(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_additional_class_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

SwiftMessageOptions::SwiftMessageOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  linkedobjects_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.protobuf.SwiftMessageOptions)
}
SwiftMessageOptions::SwiftMessageOptions(const SwiftMessageOptions& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      linkedobjects_(from.linkedobjects_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  additional_class_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_additional_class_name()) {
    additional_class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_additional_class_name(),
      GetArena());
  }
  ::memcpy(&generate_error_type_, &from.generate_error_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&generate_react_) -
    reinterpret_cast<char*>(&generate_error_type_)) + sizeof(generate_react_));
  // @@protoc_insertion_point(copy_constructor:google.protobuf.SwiftMessageOptions)
}

void SwiftMessageOptions::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SwiftMessageOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  additional_class_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&generate_error_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&generate_react_) -
      reinterpret_cast<char*>(&generate_error_type_)) + sizeof(generate_react_));
}

SwiftMessageOptions::~SwiftMessageOptions() {
  // @@protoc_insertion_point(destructor:google.protobuf.SwiftMessageOptions)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SwiftMessageOptions::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  additional_class_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SwiftMessageOptions::ArenaDtor(void* object) {
  SwiftMessageOptions* _this = reinterpret_cast< SwiftMessageOptions* >(object);
  (void)_this;
}
void SwiftMessageOptions::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SwiftMessageOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SwiftMessageOptions& SwiftMessageOptions::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SwiftMessageOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  return *internal_default_instance();
}


void SwiftMessageOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.SwiftMessageOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  linkedobjects_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    additional_class_name_.ClearNonDefaultToEmpty();
  }
  ::memset(&generate_error_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&generate_react_) -
      reinterpret_cast<char*>(&generate_error_type_)) + sizeof(generate_react_));
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SwiftMessageOptions::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool generate_error_type = 1 [default = false];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_generate_error_type(&has_bits);
          generate_error_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool generate_realm_object = 2 [default = false];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_generate_realm_object(&has_bits);
          generate_realm_object_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool generate_react = 3 [default = false];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_generate_react(&has_bits);
          generate_react_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string additional_class_name = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_additional_class_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "google.protobuf.SwiftMessageOptions.additional_class_name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .google.protobuf.LinkedObject linkedObjects = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_linkedobjects(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SwiftMessageOptions::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.SwiftMessageOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool generate_error_type = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_generate_error_type(), target);
  }

  // optional bool generate_realm_object = 2 [default = false];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_generate_realm_object(), target);
  }

  // optional bool generate_react = 3 [default = false];
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_generate_react(), target);
  }

  // optional string additional_class_name = 4;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_additional_class_name().data(), static_cast<int>(this->_internal_additional_class_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "google.protobuf.SwiftMessageOptions.additional_class_name");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_additional_class_name(), target);
  }

  // repeated .google.protobuf.LinkedObject linkedObjects = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_linkedobjects_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_linkedobjects(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.SwiftMessageOptions)
  return target;
}

size_t SwiftMessageOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.SwiftMessageOptions)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .google.protobuf.LinkedObject linkedObjects = 5;
  total_size += 1UL * this->_internal_linkedobjects_size();
  for (const auto& msg : this->linkedobjects_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string additional_class_name = 4;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_additional_class_name());
    }

    // optional bool generate_error_type = 1 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool generate_realm_object = 2 [default = false];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

    // optional bool generate_react = 3 [default = false];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SwiftMessageOptions::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.SwiftMessageOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const SwiftMessageOptions* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SwiftMessageOptions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.SwiftMessageOptions)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.SwiftMessageOptions)
    MergeFrom(*source);
  }
}

void SwiftMessageOptions::MergeFrom(const SwiftMessageOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.SwiftMessageOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  linkedobjects_.MergeFrom(from.linkedobjects_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_additional_class_name(from._internal_additional_class_name());
    }
    if (cached_has_bits & 0x00000002u) {
      generate_error_type_ = from.generate_error_type_;
    }
    if (cached_has_bits & 0x00000004u) {
      generate_realm_object_ = from.generate_realm_object_;
    }
    if (cached_has_bits & 0x00000008u) {
      generate_react_ = from.generate_react_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SwiftMessageOptions::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.SwiftMessageOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SwiftMessageOptions::CopyFrom(const SwiftMessageOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.SwiftMessageOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwiftMessageOptions::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(linkedobjects_)) return false;
  return true;
}

void SwiftMessageOptions::InternalSwap(SwiftMessageOptions* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  linkedobjects_.InternalSwap(&other->linkedobjects_);
  additional_class_name_.Swap(&other->additional_class_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SwiftMessageOptions, generate_react_)
      + sizeof(SwiftMessageOptions::generate_react_)
      - PROTOBUF_FIELD_OFFSET(SwiftMessageOptions, generate_error_type_)>(
          reinterpret_cast<char*>(&generate_error_type_),
          reinterpret_cast<char*>(&other->generate_error_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SwiftMessageOptions::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SwiftFieldOptions::InitAsDefaultInstance() {
}
class SwiftFieldOptions::_Internal {
 public:
  using HasBits = decltype(std::declval<SwiftFieldOptions>()._has_bits_);
  static void set_has_realm_indexed_propertie(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_realm_primary_key(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_realm_override_propertie(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

SwiftFieldOptions::SwiftFieldOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.protobuf.SwiftFieldOptions)
}
SwiftFieldOptions::SwiftFieldOptions(const SwiftFieldOptions& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&realm_indexed_propertie_, &from.realm_indexed_propertie_,
    static_cast<size_t>(reinterpret_cast<char*>(&realm_override_propertie_) -
    reinterpret_cast<char*>(&realm_indexed_propertie_)) + sizeof(realm_override_propertie_));
  // @@protoc_insertion_point(copy_constructor:google.protobuf.SwiftFieldOptions)
}

void SwiftFieldOptions::SharedCtor() {
  ::memset(&realm_indexed_propertie_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&realm_override_propertie_) -
      reinterpret_cast<char*>(&realm_indexed_propertie_)) + sizeof(realm_override_propertie_));
}

SwiftFieldOptions::~SwiftFieldOptions() {
  // @@protoc_insertion_point(destructor:google.protobuf.SwiftFieldOptions)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SwiftFieldOptions::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SwiftFieldOptions::ArenaDtor(void* object) {
  SwiftFieldOptions* _this = reinterpret_cast< SwiftFieldOptions* >(object);
  (void)_this;
}
void SwiftFieldOptions::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SwiftFieldOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SwiftFieldOptions& SwiftFieldOptions::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SwiftFieldOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  return *internal_default_instance();
}


void SwiftFieldOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.SwiftFieldOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&realm_indexed_propertie_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&realm_override_propertie_) -
        reinterpret_cast<char*>(&realm_indexed_propertie_)) + sizeof(realm_override_propertie_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SwiftFieldOptions::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool realm_indexed_propertie = 1 [default = false];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_realm_indexed_propertie(&has_bits);
          realm_indexed_propertie_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool realm_primary_key = 2 [default = false];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_realm_primary_key(&has_bits);
          realm_primary_key_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .google.protobuf.RealmOverrideRepeated realm_override_propertie = 3 [default = OVERRIDE];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::google::protobuf::RealmOverrideRepeated_IsValid(val))) {
            _internal_set_realm_override_propertie(static_cast<::google::protobuf::RealmOverrideRepeated>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SwiftFieldOptions::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.SwiftFieldOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool realm_indexed_propertie = 1 [default = false];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_realm_indexed_propertie(), target);
  }

  // optional bool realm_primary_key = 2 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_realm_primary_key(), target);
  }

  // optional .google.protobuf.RealmOverrideRepeated realm_override_propertie = 3 [default = OVERRIDE];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_realm_override_propertie(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.SwiftFieldOptions)
  return target;
}

size_t SwiftFieldOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.SwiftFieldOptions)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bool realm_indexed_propertie = 1 [default = false];
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 1;
    }

    // optional bool realm_primary_key = 2 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional .google.protobuf.RealmOverrideRepeated realm_override_propertie = 3 [default = OVERRIDE];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_realm_override_propertie());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SwiftFieldOptions::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.SwiftFieldOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const SwiftFieldOptions* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SwiftFieldOptions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.SwiftFieldOptions)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.SwiftFieldOptions)
    MergeFrom(*source);
  }
}

void SwiftFieldOptions::MergeFrom(const SwiftFieldOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.SwiftFieldOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      realm_indexed_propertie_ = from.realm_indexed_propertie_;
    }
    if (cached_has_bits & 0x00000002u) {
      realm_primary_key_ = from.realm_primary_key_;
    }
    if (cached_has_bits & 0x00000004u) {
      realm_override_propertie_ = from.realm_override_propertie_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SwiftFieldOptions::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.SwiftFieldOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SwiftFieldOptions::CopyFrom(const SwiftFieldOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.SwiftFieldOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwiftFieldOptions::IsInitialized() const {
  return true;
}

void SwiftFieldOptions::InternalSwap(SwiftFieldOptions* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SwiftFieldOptions, realm_override_propertie_)
      + sizeof(SwiftFieldOptions::realm_override_propertie_)
      - PROTOBUF_FIELD_OFFSET(SwiftFieldOptions, realm_indexed_propertie_)>(
          reinterpret_cast<char*>(&realm_indexed_propertie_),
          reinterpret_cast<char*>(&other->realm_indexed_propertie_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SwiftFieldOptions::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SwiftEnumOptions::InitAsDefaultInstance() {
}
class SwiftEnumOptions::_Internal {
 public:
  using HasBits = decltype(std::declval<SwiftEnumOptions>()._has_bits_);
  static void set_has_generate_error_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_generate_react(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_generate_realm_object(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

SwiftEnumOptions::SwiftEnumOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.protobuf.SwiftEnumOptions)
}
SwiftEnumOptions::SwiftEnumOptions(const SwiftEnumOptions& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&generate_error_type_, &from.generate_error_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&generate_realm_object_) -
    reinterpret_cast<char*>(&generate_error_type_)) + sizeof(generate_realm_object_));
  // @@protoc_insertion_point(copy_constructor:google.protobuf.SwiftEnumOptions)
}

void SwiftEnumOptions::SharedCtor() {
  ::memset(&generate_error_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&generate_realm_object_) -
      reinterpret_cast<char*>(&generate_error_type_)) + sizeof(generate_realm_object_));
}

SwiftEnumOptions::~SwiftEnumOptions() {
  // @@protoc_insertion_point(destructor:google.protobuf.SwiftEnumOptions)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SwiftEnumOptions::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SwiftEnumOptions::ArenaDtor(void* object) {
  SwiftEnumOptions* _this = reinterpret_cast< SwiftEnumOptions* >(object);
  (void)_this;
}
void SwiftEnumOptions::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SwiftEnumOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SwiftEnumOptions& SwiftEnumOptions::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SwiftEnumOptions_google_2fprotobuf_2fswift_2ddescriptor_2eproto.base);
  return *internal_default_instance();
}


void SwiftEnumOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.SwiftEnumOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&generate_error_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&generate_realm_object_) -
      reinterpret_cast<char*>(&generate_error_type_)) + sizeof(generate_realm_object_));
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SwiftEnumOptions::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool generate_error_type = 1 [default = false];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_generate_error_type(&has_bits);
          generate_error_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool generate_react = 2 [default = false];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_generate_react(&has_bits);
          generate_react_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool generate_realm_object = 3 [default = false];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_generate_realm_object(&has_bits);
          generate_realm_object_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SwiftEnumOptions::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.SwiftEnumOptions)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool generate_error_type = 1 [default = false];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_generate_error_type(), target);
  }

  // optional bool generate_react = 2 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_generate_react(), target);
  }

  // optional bool generate_realm_object = 3 [default = false];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_generate_realm_object(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.SwiftEnumOptions)
  return target;
}

size_t SwiftEnumOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.SwiftEnumOptions)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bool generate_error_type = 1 [default = false];
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 1;
    }

    // optional bool generate_react = 2 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool generate_realm_object = 3 [default = false];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SwiftEnumOptions::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.SwiftEnumOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const SwiftEnumOptions* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SwiftEnumOptions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.SwiftEnumOptions)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.SwiftEnumOptions)
    MergeFrom(*source);
  }
}

void SwiftEnumOptions::MergeFrom(const SwiftEnumOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.SwiftEnumOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      generate_error_type_ = from.generate_error_type_;
    }
    if (cached_has_bits & 0x00000002u) {
      generate_react_ = from.generate_react_;
    }
    if (cached_has_bits & 0x00000004u) {
      generate_realm_object_ = from.generate_realm_object_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SwiftEnumOptions::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.SwiftEnumOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SwiftEnumOptions::CopyFrom(const SwiftEnumOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.SwiftEnumOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwiftEnumOptions::IsInitialized() const {
  return true;
}

void SwiftEnumOptions::InternalSwap(SwiftEnumOptions* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SwiftEnumOptions, generate_realm_object_)
      + sizeof(SwiftEnumOptions::generate_realm_object_)
      - PROTOBUF_FIELD_OFFSET(SwiftEnumOptions, generate_error_type_)>(
          reinterpret_cast<char*>(&generate_error_type_),
          reinterpret_cast<char*>(&other->generate_error_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SwiftEnumOptions::GetMetadata() const {
  return GetMetadataStatic();
}

::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftFileOptions >, 11, false >
  swift_file_options(kSwiftFileOptionsFieldNumber, ::google::protobuf::SwiftFileOptions::default_instance());
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftFieldOptions >, 11, false >
  swift_field_options(kSwiftFieldOptionsFieldNumber, ::google::protobuf::SwiftFieldOptions::default_instance());
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftMessageOptions >, 11, false >
  swift_message_options(kSwiftMessageOptionsFieldNumber, ::google::protobuf::SwiftMessageOptions::default_instance());
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::google::protobuf::SwiftEnumOptions >, 11, false >
  swift_enum_options(kSwiftEnumOptionsFieldNumber, ::google::protobuf::SwiftEnumOptions::default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::google::protobuf::LinkedObject* Arena::CreateMaybeMessage< ::google::protobuf::LinkedObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::protobuf::LinkedObject >(arena);
}
template<> PROTOBUF_NOINLINE ::google::protobuf::SwiftFileOptions* Arena::CreateMaybeMessage< ::google::protobuf::SwiftFileOptions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::protobuf::SwiftFileOptions >(arena);
}
template<> PROTOBUF_NOINLINE ::google::protobuf::SwiftMessageOptions* Arena::CreateMaybeMessage< ::google::protobuf::SwiftMessageOptions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::protobuf::SwiftMessageOptions >(arena);
}
template<> PROTOBUF_NOINLINE ::google::protobuf::SwiftFieldOptions* Arena::CreateMaybeMessage< ::google::protobuf::SwiftFieldOptions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::protobuf::SwiftFieldOptions >(arena);
}
template<> PROTOBUF_NOINLINE ::google::protobuf::SwiftEnumOptions* Arena::CreateMaybeMessage< ::google::protobuf::SwiftEnumOptions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::protobuf::SwiftEnumOptions >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
